[package]
name = "slint-kit-gallery"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
slint = { version = "1.17", default-features = false, features = [
    "std",
    "backend-winit",
    "renderer-skia",
    "accessibility",
    "compat-1-2",
] }
slint-kit = { path = "../.." }

[build-dependencies]
slint-build = "1.17"
slint-kit = { path = "../.." }
